  name: Deploy to DreamHost via FTP

# Trigger this workflow on push events to the main branch
on:
  push:
    branches:
      - main  # Change this to your branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your repository code

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.9.0'

      - name: Install dependencies
        run: npm install  # Installs your project dependencies

      - name: Generate Nuxt project
        run: npm run generate  # Builds your project

      - name: Upload to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          source: ".output/public/"
          target: "/home/dh_8vtwft/MetropolitanElectric/" 
